### ISSUE TITLE
Issue installing in IntelliJ engine lasted version 

### ISSUE THREAD

**Issue by jruedaq** [EOM/Spell-Checking-PHPStorm-Spanish-dic-UTF8#7]
![image](https://user-images.githubusercontent.com/24756521/86410187-f2e23180-bc7f-11ea-80ec-bc6f8e1732a7.png)

**Comment by EOM** [comment]
Hi, I don't have the latest IntelliJ version, but the solution for any version is to add the dictionary manually, instead of by installing the plugin.

**English: Installation Manual** 

1. Download "spanish-utf8.dic" and save it to the folder where you have installed  "JetBrains/dic" (if there is no folder, create it).
2. Open the "Settings" window of IDE (from the "File" menu), and within the "Editor -> Spelling" section adds "spanish-utf8.dic" to the list of dictionaries:
